name: llm
channels:
  - conda-forge
dependencies:
  - notebook=6.4.12
  - pip=22.2
  - python=3.11.2
  - pip:
      - hydra-core==1.3.2
      - loguru==0.7.0
      - openai==0.27.7
      - pydash==7.0.3
      - python-dotenv==1.0.0
      - tiktoken==0.4.0
      - weaviate-client==3.19.2
